#!/usr/bin/python
import sys
import urllib2
import json
try:
    filename = sys.argv[1]
except IndexError:
    print 'Usage: transcribe.py <file>'
    sys.exit(1)

f = open(filename)
data = f.read()
f.close()

req = urllib2.Request('https://www.google.com/speech-api/v2/recognize?output=json&lang=fr-fr&key=AIzaSyCnl6MRydhw_5fLXIdASxkLJzcJh5iX0M4', data=data, headers={'Content-type': 'audio/x-flac; rate=16000'})

try:
    ret = urllib2.urlopen(req)
except urllib2.URLError:
    print "Error Transcribing Voicemail"
    sys.exit(1)

resp = ret.read()

text = json.loads(json.dumps(resp))[1]['alternative'][0]['transcript']
print text